apiVersion: apps/v1
kind: Deployment
metadata:
  name: videostore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videostore
  template:
    metadata:
      labels:
        app: videostore
    spec:
      containers:
      - name: videostore
        image: videostore-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
